Vectors and icons by <a href="https://github.com/teenyicons/teenyicons?ref=svgrepo.com" target="_blank">Teenyicons</a> in MIT License via <a href="https://www.svgrepo.com/" target="_blank">SVG Repo</a>

Vectors and icons by <a href="https://github.com/etn-ccis/blui-icons?ref=svgrepo.com" target="_blank">Etn Ccis</a> in MIT License via <a href="https://www.svgrepo.com/" target="_blank">SVG Repo</a>